// import Head from "next/head";
// import styles from "../styles/Home.module.css";
import ResponsiveAppBar from "./components/navbar";
import SwiperCarousel from "./components/header-carousel";
import ProductCarousel from "./components/index-components/product-carousel";
export default function App() {
    return (
        <div className={"container"}>
            {/* <Head>
                <title>Desicovers Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head> */}
            <main>
                <ResponsiveAppBar />
                <SwiperCarousel />
                <ProductCarousel />
            </main>

            {/* <footer className={styles.footer}></footer> */}
            <div className="py-5"></div>
        </div>
    );
}
